[workspace]

[package]
name = "symphony-sp1-program"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "symphony-sp1-program"
path = "src/main.rs"

[dependencies]
sp1-zkvm = { path = "../../../../../sp1/crates/zkvm/entrypoint" }

